<a href="https://colab.research.google.com/github/TimotheeeNiven/IntroML_TNiven/blob/main/Homework4_TNiven.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats

# use seaborn plotting defaults
import seaborn as sns; sns.set()

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
urlCancer = '/content/drive/MyDrive/IntroML/CSVFiles/cancer.csv'

cancerdataset = pd.read_csv(urlCancer)

# Display the first 5 rows of the DataFrame
print(cancerdataset.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

In [5]:
#Binary Map the outputs
def binary_map(x):
    return x.map({'M': 1, 'B': 0})
cancerdataset[['diagnosis']] = cancerdataset[['diagnosis']].apply(binary_map)

#Data set locations
X4 = cancerdataset.iloc[:, [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]].values
Y4 = cancerdataset.iloc[:, 1].values
cancerdataset.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          1        17.99         10.38          122.80     1001.0   
1    842517          1        20.57         17.77          132.90     1326.0   
2  84300903          1        19.69         21.25          130.00     1203.0   
3  84348301          1        11.42         20.38           77.58      386.1   
4  84358402          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
# Split the data into a training and testing set
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, Y4, test_size=0.2, random_state=0)

In [7]:
# "Linear Support vector classifier"
from sklearn.svm import SVC
model = SVC(kernel='linear', C=200)
model.fit(X_train4, y_train4)

SVC(C=200, kernel='linear')

In [8]:
#Determine the PRF1 of PCA
from sklearn import datasets
from sklearn import metrics

# Apply PCA
pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train4)
X_test_pca = pca.transform(X_test4)

model.fit(X_train_pca,y_train4)
expected4 = y_test4
predicted4 = model.predict(X_test_pca)
# summarize the fit of the model
print(metrics.classification_report(expected4, predicted4))
print(metrics.confusion_matrix(expected4, predicted4))

              precision    recall  f1-score   support

           0       0.98      0.93      0.95        67
           1       0.90      0.98      0.94        47

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114

[[62  5]
 [ 1 46]]


In [9]:
clf = SVC(kernel='rbf', C=200)
clf.fit(X_train_pca, y_train4)
expected4a = y_test4
predicted4a = clf.predict(X_test_pca)
# summarize the fit of the model
print(metrics.classification_report(expected4a, predicted4a))
print(metrics.confusion_matrix(expected4a, predicted4a))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        67
           1       0.94      0.94      0.94        47

    accuracy                           0.95       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114

[[64  3]
 [ 3 44]]


In [10]:
clf2 = SVC(kernel='poly', C=200)
clf2.fit(X_train_pca, y_train4)
expected4b = y_test4
predicted4b = clf2.predict(X_test_pca)
# summarize the fit of the model
print(metrics.classification_report(expected4b, predicted4b))
print(metrics.confusion_matrix(expected4b, predicted4b))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        67
           1       1.00      0.66      0.79        47

    accuracy                           0.86       114
   macro avg       0.90      0.83      0.84       114
weighted avg       0.89      0.86      0.85       114

[[67  0]
 [16 31]]


In [11]:
clf3 = SVC(kernel='sigmoid', C=200)
clf3.fit(X_train_pca, y_train4)
expected4c = y_test4
predicted4c = clf3.predict(X_test_pca)
# summarize the fit of the model
print(metrics.classification_report(expected4c, predicted4c))
print(metrics.confusion_matrix(expected4c, predicted4c))

              precision    recall  f1-score   support

           0       0.95      0.82      0.88        67
           1       0.79      0.94      0.85        47

    accuracy                           0.87       114
   macro avg       0.87      0.88      0.87       114
weighted avg       0.88      0.87      0.87       114

[[55 12]
 [ 3 44]]


Problem 2 (50pts):

Develop a SVR regression model that predicts housing price based on the following input variables:

Area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea


In [12]:
# Use the URL for the raw CSV data -- more datasets can be find here: https://github.com/satishgunjal/datasets
urlHouse = '/content/drive/MyDrive/IntroML/CSVFiles/Housing.csv'

df = pd.read_csv(urlHouse)

# Display the first 5 rows of the DataFrame
print(df.head())

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  


In [13]:
# List of variables to map

varlist =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus']

# Defining the map function
def binary_map(x):
    return x.map({'yes': 1, 'no': 0, 'furnished': 2, 'semi-furnished': 1, 'unfurnished': 0})
# Defining the map function for furnishing status

# Applying the function to the housing list
df[varlist] = df[varlist].apply(binary_map)
df.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 2  
1                 2  
2                 1  
3                 2  
4                 2

In [23]:
#Seperate the X and Y variables
X4b = df.iloc[:, [1,2,3,4,5,6,7,8,9,10,11]].values
Y4b = df.iloc[:, 0].values

In [15]:
# Split the data into a training and testing set
X_train4b, X_test4b, y_train4b, y_test4b = train_test_split(X4b, Y4b, test_size=0.2, random_state=0)

# Apply PCA
pca = PCA(n_components=5)
X_train_pca1 = pca.fit_transform(X_train4b)
X_test_pca1 = pca.transform(X_test4b)

In [27]:
from sklearn.svm import SVR

# Create SVR models with different kernels
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_lin = SVR(kernel='linear', C=1e3)
svr_poly = SVR(kernel='poly', C=1e3, degree=2)

# Fit the SVR models to your data
y_rbf = svr_rbf.fit(X_train_pca1, y_train4b).predict(X_train_pca1)
y_lin = svr_lin.fit(X_train_pca1, y_train4b).predict(X_train_pca1)
y_poly = svr_poly.fit(X_train_pca1, y_train4b).predict(X_train_pca1)